#!/bin/bash
set -x
`python arff2VWConverter.py \
  /home/caglar/Documents/Datasets/GN3_TrafficClassification/gtvs/Day1.TCP.arff \
  ../../../../test/datasets/gtvs/gtvs.train ../../../../test/arfx/gtvs.arfx`

`python arff2VWConverter.py \
  /home/caglar/Documents/Datasets/GN3_TrafficClassification/gtvs/Day2.TCP.arff \
  ../../../../test/datasets/gtvs/gtvs.test ../../../../test/arfx/gtvs2.arfx`
